name: Team4 Action
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: |
          mvn test -Dtest=devops.codereview.QueryOneTest
          mvn test -Dtest=devops.codereview.QueryTwoTest
          mvn test -Dtest=devops.codereview.QueryThreeTest
          mvn test -Dtest=devops.codereview.QueryFourTest
          mvn test -Dtest=devops.codereview.QueryFiveTest
          mvn test -Dtest=devops.codereview.QuerySixTest
          mvn test -Dtest=devops.codereview.QuerySevenTest
          mvn test -Dtest=devops.codereview.QueryEightTest
          mvn test -Dtest=devops.codereview.QueryNineTest
          mvn test -Dtest=devops.codereview.QueryTenTest
          mvn test -Dtest=devops.codereview.QueryElevenTest
          mvn test -Dtest=devops.codereview.QueryTwelveTest
          mvn test -Dtest=devops.codereview.QueryThirteenTest
          mvn test -Dtest=devops.codereview.QueryFourteenTest
          mvn test -Dtest=devops.codereview.QueryFifteenTest
          mvn test -Dtest=devops.codereview.QuerySixteenTest
          mvn test -Dtest=devops.codereview.QuerySeventeenTest
          mvn test -Dtest=devops.codereview.QueryEighteenTest
          mvn test -Dtest=devops.codereview.QueryNineteenTest
          mvn test -Dtest=devops.codereview.QueryTwentyTest
          mvn test -Dtest=devops.codereview.QueryTwentyOneTest
          mvn test -Dtest=devops.codereview.QueryTwentyTwoTest
          mvn test -Dtest=devops.codereview.QueryTwentyThreeTest
          mvn test -Dtest=devops.codereview.QueryTwentyFourTest
          mvn test -Dtest=devops.codereview.QueryTwentyFiveTest
          mvn test -Dtest=devops.codereview.QueryTwentySixTest
          mvn test -Dtest=devops.codereview.QueryTwentySevenTest
          mvn test -Dtest=devops.codereview.QueryTwentyEightTest
          mvn test -Dtest=devops.codereview.QueryTwentyNineTest
          mvn test -Dtest=devops.codereview.QueryThirtyTest
          mvn test -Dtest=devops.codereview.QueryThirtyOneTest
          mvn test -Dtest=devops.codereview.QueryThirtyTwoTest
  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Integration Tests and CodeCov
        run: |
          docker build -t database ./db 
          docker run --name world -dp 33060:3306 database
          mvn test -Dtest=devops.codereview.CapitalCityIntegrationTest
          mvn test -Dtest=devops.codereview.CountryIntegrationTest
          mvn test -Dtest=devops.codereview.CityIntegrationTest 
          mvn test -Dtest=devops.codereview.PeoplePopulationIntegrationTest
          docker stop world
          docker rm world
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./target/site/jacoco
          flags: IntegrationTests # optional
          verbose: true # optional (default = false)

  build:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar

